name: Docs

on: [push]

jobs:
  docs:
    name: Docs with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Update pip
        run: |
          pip install --upgrade pip
          pip install --upgrade pytz
          pip install --upgrade tzdata
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run sphinx-apidoc
        working-directory: ./docs
        run: |
          sphinx-apidoc -o source ../uniswap -M -f
      - name: Run sphinx-apidoc
        working-directory: ./docs
        run: |
          make clean
          make html
